 

// src/utils/countryCodes.ts
export interface CountryCode {
  name: string;
  dial_code: string;
  code: string;
  flag: string;
}
const countryCodes: Record<string, CountryCode> = {
 
  
/* // src/utils/countryCodes.js
 


// JS version


const countryCodes = { */
    AF: { name: 'Afghanistan', dial_code: '+93', code: 'AF', flag: '🇦🇫' },
    AL: { name: 'Albania', dial_code: '+355', code: 'AL', flag: '🇦🇱' },
    DZ: { name: 'Algeria', dial_code: '+213', code: 'DZ', flag: '🇩🇿' },
    AS: { name: 'American Samoa', dial_code: '+1684', code: 'AS', flag: '🇦🇸' },
    AD: { name: 'Andorra', dial_code: '+376', code: 'AD', flag: '🇦🇩' },
    AO: { name: 'Angola', dial_code: '+244', code: 'AO', flag: '🇦🇴' },
    AI: { name: 'Anguilla', dial_code: '+1264', code: 'AI', flag: '🇦🇮' },
    AG: { name: 'Antigua and Barbuda', dial_code: '+1268', code: 'AG', flag: '🇦🇬' },
    AR: { name: 'Argentina', dial_code: '+54', code: 'AR', flag: '🇦🇷' },
    AM: { name: 'Armenia', dial_code: '+374', code: 'AM', flag: '🇦🇲' },
    AW: { name: 'Aruba', dial_code: '+297', code: 'AW', flag: '🇦🇼' },
    AU: { name: 'Australia', dial_code: '+61', code: 'AU', flag: '🇦🇺' },
    AT: { name: 'Austria', dial_code: '+43', code: 'AT', flag: '🇦🇹' },
    AZ: { name: 'Azerbaijan', dial_code: '+994', code: 'AZ', flag: '🇦🇿' },
    BS: { name: 'Bahamas', dial_code: '+1242', code: 'BS', flag: '🇧🇸' },
    BH: { name: 'Bahrain', dial_code: '+973', code: 'BH', flag: '🇧🇭' },
    BD: { name: 'Bangladesh', dial_code: '+880', code: 'BD', flag: '🇧🇩' },
    BB: { name: 'Barbados', dial_code: '+1246', code: 'BB', flag: '🇧🇧' },
    BY: { name: 'Belarus', dial_code: '+375', code: 'BY', flag: '🇧🇾' },
    BE: { name: 'Belgium', dial_code: '+32', code: 'BE', flag: '🇧🇪' },
    BZ: { name: 'Belize', dial_code: '+501', code: 'BZ', flag: '🇧🇿' },
    BJ: { name: 'Benin', dial_code: '+229', code: 'BJ', flag: '🇧🇯' },
    BM: { name: 'Bermuda', dial_code: '+1441', code: 'BM', flag: '🇧🇲' },
    BT: { name: 'Bhutan', dial_code: '+975', code: 'BT', flag: '🇧🇹' },
    BO: { name: 'Bolivia', dial_code: '+591', code: 'BO', flag: '🇧🇴' },
    BA: { name: 'Bosnia and Herzegovina', dial_code: '+387', code: 'BA', flag: '🇧🇦' },
    BW: { name: 'Botswana', dial_code: '+267', code: 'BW', flag: '🇧🇼' },
    BR: { name: 'Brazil', dial_code: '+55', code: 'BR', flag: '🇧🇷' },
    IO: { name: 'British Indian Ocean Territory', dial_code: '+246', code: 'IO', flag: '🇮🇴' },
    BN: { name: 'Brunei Darussalam', dial_code: '+673', code: 'BN', flag: '🇧🇳' },
    BG: { name: 'Bulgaria', dial_code: '+359', code: 'BG', flag: '🇧🇬' },
    BF: { name: 'Burkina Faso', dial_code: '+226', code: 'BF', flag: '🇧🇫' },
    BI: { name: 'Burundi', dial_code: '+257', code: 'BI', flag: '🇧🇮' },
    KH: { name: 'Cambodia', dial_code: '+855', code: 'KH', flag: '🇰🇭' },
    CM: { name: 'Cameroon', dial_code: '+237', code: 'CM', flag: '🇨🇲' },
    CA: { name: 'Canada', dial_code: '+1', code: 'CA', flag: '🇨🇦' },
    CV: { name: 'Cape Verde', dial_code: '+238', code: 'CV', flag: '🇨🇻' },
    KY: { name: 'Cayman Islands', dial_code: '+1345', code: 'KY', flag: '🇰🇾' },
    CF: { name: 'Central African Republic', dial_code: '+236', code: 'CF', flag: '🇨🇫' },
    TD: { name: 'Chad', dial_code: '+235', code: 'TD', flag: '🇹🇩' },
    CL: { name: 'Chile', dial_code: '+56', code: 'CL', flag: '🇨🇱' },
    CN: { name: 'China', dial_code: '+86', code: 'CN', flag: '🇨🇳' },
    CX: { name: 'Christmas Island', dial_code: '+61', code: 'CX', flag: '🇨🇽' },
    CC: { name: 'Cocos (Keeling) Islands', dial_code: '+61', code: 'CC', flag: '🇨🇨' },
    CO: { name: 'Colombia', dial_code: '+57', code: 'CO', flag: '🇨🇴' },
    KM: { name: 'Comoros', dial_code: '+269', code: 'KM', flag: '🇰🇲' },
    CG: { name: 'Congo', dial_code: '+242', code: 'CG', flag: '🇨🇬' },
    CD: { name: 'Congo, The Democratic Republic of the', dial_code: '+243', code: 'CD', flag: '🇨🇩' },
    CK: { name: 'Cook Islands', dial_code: '+682', code: 'CK', flag: '🇨🇰' },
    CR: { name: 'Costa Rica', dial_code: '+506', code: 'CR', flag: '🇨🇷' },
    CI: { name: "Cote d'Ivoire", dial_code: '+225', code: 'CI', flag: '🇨🇮' },
    HR: { name: 'Croatia', dial_code: '+385', code: 'HR', flag: '🇭🇷' },
    CU: { name: 'Cuba', dial_code: '+53', code: 'CU', flag: '🇨🇺' },
    CY: { name: 'Cyprus', dial_code: '+357', code: 'CY', flag: '🇨🇾' },
    CZ: { name: 'Czech Republic', dial_code: '+420', code: 'CZ', flag: '🇨🇿' },
    DK: { name: 'Denmark', dial_code: '+45', code: 'DK', flag: '🇩🇰' },
    DJ: { name: 'Djibouti', dial_code: '+253', code: 'DJ', flag: '🇩🇯' },
    DM: { name: 'Dominica', dial_code: '+1767', code: 'DM', flag: '🇩🇲' },
    DO: { name: 'Dominican Republic', dial_code: '+1849', code: 'DO', flag: '🇩🇴' },
    EC: { name: 'Ecuador', dial_code: '+593', code: 'EC', flag: '🇪🇨' },
    EG: { name: 'Egypt', dial_code: '+20', code: 'EG', flag: '🇪🇬' },
    SV: { name: 'El Salvador', dial_code: '+503', code: 'SV', flag: '🇸🇻' },
    GQ: { name: 'Equatorial Guinea', dial_code: '+240', code: 'GQ', flag: '🇬🇶' },
    ER: { name: 'Eritrea', dial_code: '+291', code: 'ER', flag: '🇪🇷' },
    EE: { name: 'Estonia', dial_code: '+372', code: 'EE', flag: '🇪🇪' },
    ET: { name: 'Ethiopia', dial_code: '+251', code: 'ET', flag: '🇪🇹' },
    FK: { name: 'Falkland Islands (Malvinas)', dial_code: '+500', code: 'FK', flag: '🇫🇰' },
    FO: { name: 'Faroe Islands', dial_code: '+298', code: 'FO', flag: '🇫🇴' },
    FJ: { name: 'Fiji', dial_code: '+679', code: 'FJ', flag: '🇫🇯' },
    FI: { name: 'Finland', dial_code: '+358', code: 'FI', flag: '🇫🇮' },
    FR: { name: 'France', dial_code: '+33', code: 'FR', flag: '🇫🇷' },
    GF: { name: 'French Guiana', dial_code: '+594', code: 'GF', flag: '🇬🇫' },
    PF: { name: 'French Polynesia', dial_code: '+689', code: 'PF', flag: '🇵🇫' },
    GA: { name: 'Gabon', dial_code: '+241', code: 'GA', flag: '🇬🇦' },
    GM: { name: 'Gambia', dial_code: '+220', code: 'GM', flag: '🇬🇲' },
    GE: { name: 'Georgia', dial_code: '+995', code: 'GE', flag: '🇬🇪' },
    DE: { name: 'Germany', dial_code: '+49', code: 'DE', flag: '🇩🇪' },
    GH: { name: 'Ghana', dial_code: '+233', code: 'GH', flag: '🇬🇭' },
    GI: { name: 'Gibraltar', dial_code: '+350', code: 'GI', flag: '🇬🇮' },
    GR: { name: 'Greece', dial_code: '+30', code: 'GR', flag: '🇬🇷' },
    GL: { name: 'Greenland', dial_code: '+299', code: 'GL', flag: '🇬🇱' },
    GD: { name: 'Grenada', dial_code: '+1473', code: 'GD', flag: '🇬🇩' },
    GP: { name: 'Guadeloupe', dial_code: '+590', code: 'GP', flag: '🇬🇵' },
    GU: { name: 'Guam', dial_code: '+1671', code: 'GU', flag: '🇬🇺' },
    GT: { name: 'Guatemala', dial_code: '+502', code: 'GT', flag: '🇬🇹' },
    GG: { name: 'Guernsey', dial_code: '+44', code: 'GG', flag: '🇬🇬' },
    GN: { name: 'Guinea', dial_code: '+224', code: 'GN', flag: '🇬🇳' },
    GW: { name: 'Guinea-Bissau', dial_code: '+245', code: 'GW', flag: '🇬🇼' },
    GY: { name: 'Guyana', dial_code: '+592', code: 'GY', flag: '🇬🇾' },
    HT: { name: 'Haiti', dial_code: '+509', code: 'HT', flag: '🇭🇹' },
    HN: { name: 'Honduras', dial_code: '+504', code: 'HN', flag: '🇭🇳' },
    HK: { name: 'Hong Kong', dial_code: '+852', code: 'HK', flag: '🇭🇰' },
    HU: { name: 'Hungary', dial_code: '+36', code: 'HU', flag: '🇭🇺' },
    IS: { name: 'Iceland', dial_code: '+354', code: 'IS', flag: '🇮🇸' },
    IN: { name: 'India', dial_code: '+91', code: 'IN', flag: '🇮🇳' },
    ID: { name: 'Indonesia', dial_code: '+62', code: 'ID', flag: '🇮🇩' },
    IR: { name: 'Iran, Islamic Republic of', dial_code: '+98', code: 'IR', flag: '🇮🇷' },
    IQ: { name: 'Iraq', dial_code: '+964', code: 'IQ', flag: '🇮🇶' },
    IE: { name: 'Ireland', dial_code: '+353', code: 'IE', flag: '🇮🇪' },
    IM: { name: 'Isle of Man', dial_code: '+44', code: 'IM', flag: '🇮🇲' },
    IL: { name: 'Israel', dial_code: '+972', code: 'IL', flag: '🇮🇱' },
    IT: { name: 'Italy', dial_code: '+39', code: 'IT', flag: '🇮🇹' },
    JM: { name: 'Jamaica', dial_code: '+1876', code: 'JM', flag: '🇯🇲' },
    JP: { name: 'Japan', dial_code: '+81', code: 'JP', flag: '🇯🇵' },
    JE: { name: 'Jersey', dial_code: '+44', code: 'JE', flag: '🇯🇪' },
    JO: { name: 'Jordan', dial_code: '+962', code: 'JO', flag: '🇯🇴' },
    KZ: { name: 'Kazakhstan', dial_code: '+7', code: 'KZ', flag: '🇰🇿' },
    KE: { name: 'Kenya', dial_code: '+254', code: 'KE', flag: '🇰🇪' },
    KI: { name: 'Kiribati', dial_code: '+686', code: 'KI', flag: '🇰🇮' },
    KP: { name: "Korea, Democratic People's Republic of", dial_code: '+850', code: 'KP', flag: '🇰🇵' },
    KR: { name: 'Korea, Republic of', dial_code: '+82', code: 'KR', flag: '🇰🇷' },
    KW: { name: 'Kuwait', dial_code: '+965', code: 'KW', flag: '🇰🇼' },
    KG: { name: 'Kyrgyzstan', dial_code: '+996', code: 'KG', flag: '🇰🇬' },
    LA: { name: "Lao People's Democratic Republic", dial_code: '+856', code: 'LA', flag: '🇱🇦' },
    LV: { name: 'Latvia', dial_code: '+371', code: 'LV', flag: '🇱🇻' },
    LB: { name: 'Lebanon', dial_code: '+961', code: 'LB', flag: '🇱🇧' },
    LS: { name: 'Lesotho', dial_code: '+266', code: 'LS', flag: '🇱🇸' },
    LR: { name: 'Liberia', dial_code: '+231', code: 'LR', flag: '🇱🇷' },
    LY: { name: 'Libyan Arab Jamahiriya', dial_code: '+218', code: 'LY', flag: '🇱🇾' },
    LI: { name: 'Liechtenstein', dial_code: '+423', code: 'LI', flag: '🇱🇮' },
    LT: { name: 'Lithuania', dial_code: '+370', code: 'LT', flag: '🇱🇹' },
    LU: { name: 'Luxembourg', dial_code: '+352', code: 'LU', flag: '🇱🇺' },
    MO: { name: 'Macao', dial_code: '+853', code: 'MO', flag: '🇲🇴' },
    MK: { name: 'Macedonia, The Former Yugoslav Republic of', dial_code: '+389', code: 'MK', flag: '🇲🇰' },
    MG: { name: 'Madagascar', dial_code: '+261', code: 'MG', flag: '🇲🇬' },
    MW: { name: 'Malawi', dial_code: '+265', code: 'MW', flag: '🇲🇼' },
    MY: { name: 'Malaysia', dial_code: '+60', code: 'MY', flag: '🇲🇾' },
    MV: { name: 'Maldives', dial_code: '+960', code: 'MV', flag: '🇲🇻' },
    ML: { name: 'Mali', dial_code: '+223', code: 'ML', flag: '🇲🇱' },
    MT: { name: 'Malta', dial_code: '+356', code: 'MT', flag: '🇲🇹' },
    MH: { name: 'Marshall Islands', dial_code: '+692', code: 'MH', flag: '🇲🇭' },
    MQ: { name: 'Martinique', dial_code: '+596', code: 'MQ', flag: '🇲🇶' },
    MR: { name: 'Mauritania', dial_code: '+222', code: 'MR', flag: '🇲🇷' },
    MU: { name: 'Mauritius', dial_code: '+230', code: 'MU', flag: '🇲🇺' },
    YT: { name: 'Mayotte', dial_code: '+262', code: 'YT', flag: '🇾🇹' },
    MX: { name: 'Mexico', dial_code: '+52', code: 'MX', flag: '🇲🇽' },
    FM: { name: 'Micronesia, Federated States of', dial_code: '+691', code: 'FM', flag: '🇫🇲' },
    MD: { name: 'Moldova, Republic of', dial_code: '+373', code: 'MD', flag: '🇲🇩' },
    MC: { name: 'Monaco', dial_code: '+377', code: 'MC', flag: '🇲🇨' },
    MN: { name: 'Mongolia', dial_code: '+976', code: 'MN', flag: '🇲🇳' },
    ME: { name: 'Montenegro', dial_code: '+382', code: 'ME', flag: '🇲🇪' },
    MS: { name: 'Montserrat', dial_code: '+1664', code: 'MS', flag: '🇲🇸' },
    MA: { name: 'Morocco', dial_code: '+212', code: 'MA', flag: '🇲🇦' },
    MZ: { name: 'Mozambique', dial_code: '+258', code: 'MZ', flag: '🇲🇿' },
    MM: { name: 'Myanmar', dial_code: '+95', code: 'MM', flag: '🇲🇲' },
    NA: { name: 'Namibia', dial_code: '+264', code: 'NA', flag: '🇳🇦' },
    NR: { name: 'Nauru', dial_code: '+674', code: 'NR', flag: '🇳🇷' },
    NP: { name: 'Nepal', dial_code: '+977', code: 'NP', flag: '🇳🇵' },
    NL: { name: 'Netherlands', dial_code: '+31', code: 'NL', flag: '🇳🇱' },
    NC: { name: 'New Caledonia', dial_code: '+687', code: 'NC', flag: '🇳🇨' },
    NZ: { name: 'New Zealand', dial_code: '+64', code: 'NZ', flag: '🇳🇿' },
    NI: { name: 'Nicaragua', dial_code: '+505', code: 'NI', flag: '🇳🇮' },
    NE: { name: 'Niger', dial_code: '+227', code: 'NE', flag: '🇳🇪' },
    NG: { name: 'Nigeria', dial_code: '+234', code: 'NG', flag: '🇳🇬' },
    NU: { name: 'Niue', dial_code: '+683', code: 'NU', flag: '🇳🇺' },
    NF: { name: 'Norfolk Island', dial_code: '+672', code: 'NF', flag: '🇳🇫' },
    MP: { name: 'Northern Mariana Islands', dial_code: '+1670', code: 'MP', flag: '🇲🇵' },
    NO: { name: 'Norway', dial_code: '+47', code: 'NO', flag: '🇳🇴' },
    OM: { name: 'Oman', dial_code: '+968', code: 'OM', flag: '🇴🇲' },
    PK: { name: 'Pakistan', dial_code: '+92', code: 'PK', flag: '🇵🇰' },
    PW: { name: 'Palau', dial_code: '+680', code: 'PW', flag: '🇵🇼' },
    PS: { name: 'Palestinian Territory, Occupied', dial_code: '+970', code: 'PS', flag: '🇵🇸' },
    PA: { name: 'Panama', dial_code: '+507', code: 'PA', flag: '🇵🇦' },
    PG: { name: 'Papua New Guinea', dial_code: '+675', code: 'PG', flag: '🇵🇬' },
    PY: { name: 'Paraguay', dial_code: '+595', code: 'PY', flag: '🇵🇾' },
    PE: { name: 'Peru', dial_code: '+51', code: 'PE', flag: '🇵🇪' },
    PH: { name: 'Philippines', dial_code: '+63', code: 'PH', flag: '🇵🇭' },
    PN: { name: 'Pitcairn', dial_code: '+64', code: 'PN', flag: '🇵🇳' },
    PL: { name: 'Poland', dial_code: '+48', code: 'PL', flag: '🇵🇱' },
    PT: { name: 'Portugal', dial_code: '+351', code: 'PT', flag: '🇵🇹' },
    PR: { name: 'Puerto Rico', dial_code: '+1939', code: 'PR', flag: '🇵🇷' },
    QA: { name: 'Qatar', dial_code: '+974', code: 'QA', flag: '🇶🇦' },
    RE: { name: 'Reunion', dial_code: '+262', code: 'RE', flag: '🇷🇪' },
    RO: { name: 'Romania', dial_code: '+40', code: 'RO', flag: '🇷🇴' },
    RU: { name: 'Russian Federation', dial_code: '+7', code: 'RU', flag: '🇷🇺' },
    RW: { name: 'Rwanda', dial_code: '+250', code: 'RW', flag: '🇷🇼' },
    BL: { name: 'Saint Barthelemy', dial_code: '+590', code: 'BL', flag: '🇧🇱' },
    SH: { name: 'Saint Helena', dial_code: '+290', code: 'SH', flag: '🇸🇭' },
    KN: { name: 'Saint Kitts and Nevis', dial_code: '+1869', code: 'KN', flag: '🇰🇳' },
    LC: { name: 'Saint Lucia', dial_code: '+1758', code: 'LC', flag: '🇱🇨' },
    MF: { name: 'Saint Martin', dial_code: '+590', code: 'MF', flag: '🇲🇫' },
    PM: { name: 'Saint Pierre and Miquelon', dial_code: '+508', code: 'PM', flag: '🇵🇲' },
    VC: { name: 'Saint Vincent and the Grenadines', dial_code: '+1784', code: 'VC', flag: '🇻🇨' },
    WS: { name: 'Samoa', dial_code: '+685', code: 'WS', flag: '🇼🇸' },
    SM: { name: 'San Marino', dial_code: '+378', code: 'SM', flag: '🇸🇲' },
    ST: { name: 'Sao Tome and Principe', dial_code: '+239', code: 'ST', flag: '🇸🇹' },
    SA: { name: 'Saudi Arabia', dial_code: '+966', code: 'SA', flag: '🇸🇦' },
    SN: { name: 'Senegal', dial_code: '+221', code: 'SN', flag: '🇸🇳' },
    RS: { name: 'Serbia', dial_code: '+381', code: 'RS', flag: '🇷🇸' },
    SC: { name: 'Seychelles', dial_code: '+248', code: 'SC', flag: '🇸🇨' },
    SL: { name: 'Sierra Leone', dial_code: '+232', code: 'SL', flag: '🇸🇱' },
    SG: { name: 'Singapore', dial_code: '+65', code: 'SG', flag: '🇸🇬' },
    SK: { name: 'Slovakia', dial_code: '+421', code: 'SK', flag: '🇸🇰' },
    SI: { name: 'Slovenia', dial_code: '+386', code: 'SI', flag: '🇸🇮' },
    SB: { name: 'Solomon Islands', dial_code: '+677', code: 'SB', flag: '🇸🇧' },
    SO: { name: 'Somalia', dial_code: '+252', code: 'SO', flag: '🇸🇴' },
    ZA: { name: 'South Africa', dial_code: '+27', code: 'ZA', flag: '🇿🇦' },
    ES: { name: 'Spain', dial_code: '+34', code: 'ES', flag: '🇪🇸' },
    LK: { name: 'Sri Lanka', dial_code: '+94', code: 'LK', flag: '🇱🇰' },
    SD: { name: 'Sudan', dial_code: '+249', code: 'SD', flag: '🇸🇩' },
    SR: { name: 'Suriname', dial_code: '+597', code: 'SR', flag: '🇸🇷' },
    SZ: { name: 'Swaziland', dial_code: '+268', code: 'SZ', flag: '🇸🇿' },
    SE: { name: 'Sweden', dial_code: '+46', code: 'SE', flag: '🇸🇪' },
    CH: { name: 'Switzerland', dial_code: '+41', code: 'CH', flag: '🇨🇭' },
    SY: { name: 'Syrian Arab Republic', dial_code: '+963', code: 'SY', flag: '🇸🇾' },
    TW: { name: 'Taiwan, Province of China', dial_code: '+886', code: 'TW', flag: '🇹🇼' },
    TJ: { name: 'Tajikistan', dial_code: '+992', code: 'TJ', flag: '🇹🇯' },
    TZ: { name: 'Tanzania, United Republic of', dial_code: '+255', code: 'TZ', flag: '🇹🇿' },
    TH: { name: 'Thailand', dial_code: '+66', code: 'TH', flag: '🇹🇭' },
    TL: { name: 'Timor-Leste', dial_code: '+670', code: 'TL', flag: '🇹🇱' },
    TG: { name: 'Togo', dial_code: '+228', code: 'TG', flag: '🇹🇬' },
    TK: { name: 'Tokelau', dial_code: '+690', code: 'TK', flag: '🇹🇰' },
    TO: { name: 'Tonga', dial_code: '+676', code: 'TO', flag: '🇹🇴' },
    TT: { name: 'Trinidad and Tobago', dial_code: '+1868', code: 'TT', flag: '🇹🇹' },
    TN: { name: 'Tunisia', dial_code: '+216', code: 'TN', flag: '🇹🇳' },
    TR: { name: 'Turkey', dial_code: '+90', code: 'TR', flag: '🇹🇷' },
    TM: { name: 'Turkmenistan', dial_code: '+993', code: 'TM', flag: '🇹🇲' },
    TC: { name: 'Turks and Caicos Islands', dial_code: '+1649', code: 'TC', flag: '🇹🇨' },
    TV: { name: 'Tuvalu', dial_code: '+688', code: 'TV', flag: '🇹🇻' },
    UG: { name: 'Uganda', dial_code: '+256', code: 'UG', flag: '🇺🇬' },
    UA: { name: 'Ukraine', dial_code: '+380', code: 'UA', flag: '🇺🇦' },
    AE: { name: 'United Arab Emirates', dial_code: '+971', code: 'AE', flag: '🇦🇪' },
    GB: { name: 'United Kingdom', dial_code: '+44', code: 'GB', flag: '🇬🇧' },
    US: { name: 'United States', dial_code: '+1', code: 'US', flag: '🇺🇸' },
    UY: { name: 'Uruguay', dial_code: '+598', code: 'UY', flag: '🇺🇾' },
    UZ: { name: 'Uzbekistan', dial_code: '+998', code: 'UZ', flag: '🇺🇿' },
    VU: { name: 'Vanuatu', dial_code: '+678', code: 'VU', flag: '🇻🇺' },
    VE: { name: 'Venezuela, Bolivarian Republic of', dial_code: '+58', code: 'VE', flag: '🇻🇪' },
    VN: { name: 'Vietnam', dial_code: '+84', code: 'VN', flag: '🇻🇳' },
    VG: { name: 'Virgin Islands, British', dial_code: '+1284', code: 'VG', flag: '🇻🇬' },
    VI: { name: 'Virgin Islands, U.S.', dial_code: '+1340', code: 'VI', flag: '🇻🇮' },
    WF: { name: 'Wallis and Futuna', dial_code: '+681', code: 'WF', flag: '🇼🇫' },
    YE: { name: 'Yemen', dial_code: '+967', code: 'YE', flag: '🇾🇪' },
    ZM: { name: 'Zambia', dial_code: '+260', code: 'ZM', flag: '🇿🇲' },
    ZW: { name: 'Zimbabwe', dial_code: '+263', code: 'ZW', flag: '🇿🇼' },
    // You can add more countries if needed
  };
  
  export default countryCodes;
  
  